// Public surface of the domain layer. UI/API code imports from here only.
export * from "./errors";
export * from "./context";
export * from "./validation";
export * from "./auth/permissions";
export * from "./auth/password";
export * from "./auth/session";
export * from "./platform/audit";
export * from "./platform/numbering";
export * from "./platform/pagination";
export * from "./platform/state-machine";
export * as users from "./modules/users";
export * as roles from "./modules/roles";
export * as settings from "./modules/settings";
export * as auditLogs from "./modules/audit-logs";
export * as lookups from "./modules/lookups";
export * as showrooms from "./modules/showrooms";
export * as customers from "./modules/customers";
export * as suppliers from "./modules/suppliers";
export * as materials from "./modules/materials";
export * as warehouses from "./modules/warehouses";
export * as products from "./modules/products";
export * as attachments from "./modules/attachments";
export * as pricing from "./modules/pricing";
export * as quotations from "./modules/quotations";
export * as salesOrders from "./modules/sales-orders";
export * as cashAccounts from "./modules/cash-accounts";
export * as receivables from "./modules/receivables";
export * as documents from "./modules/documents";
export * as bom from "./modules/bom";
export * as measurements from "./modules/measurements";
export * as manufacturing from "./modules/manufacturing";
export * as inventory from "./modules/inventory";
export * as productionStages from "./modules/production-stages";
export * as purchasing from "./modules/purchasing";
export * as expenses from "./modules/expenses";
export * as deliveries from "./modules/deliveries";
export * as notifications from "./modules/notifications";
export * as jobs from "./modules/jobs";
export * as dashboard from "./modules/dashboard";
export * as reports from "./modules/reports";
export type { ReportResult, ReportColumn } from "./modules/reports";
export * from "./platform/formula";
export * from "./platform/inventory";
export type { DocModel } from "./modules/documents";
export * from "./platform/money";
export * from "./platform/storage";
export * from "./platform/query";
